---
title: "data_manipulation with 'dyplr'"
output: github_document
date: "2022-09-22"
---


```{r}
library(tidyverse)
library(readxl)
library(haven)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    echo = TRUE)

options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv")
litters_data = 
    janitor::clean_names(litters_data)

## :: means accessing a specific function (ie clean_names) from the janitor package, and applies it to (litters_data)

pups_data = read_csv("./data/FAS_pups.csv")
pupts_data = 
    janitor::clean_names(pups_data)
```

```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
```

```{r}
select(litters_data, group:gd_of_birth)
```

```{r}
select(litters_data, -pups_survive)
```

```{r}
select(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)
```

```{r}
rename(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)
```

```{r}
select(litters_data, starts_with("gd"))
select(litters_data, ends_with("weight"))
```

```{r}
select(litters_data, litter_number, pups_survive, everything())
```

```{r}
filter(litters_data, gd_of_birth == 20)
```

```{r}
#litter_data2
mutate(litters_data,
        wt_gain = gd18_weight - gd0_weight,
        group = str_to_lower(group),
       # wt_gain_kg = wt_gain * 2.2
)
```

```{r}
litters_data = 
    read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
    janitor::clean_names() %>%
    select(-pups_survive) %>%
    mutate(
        wt_gain = gd18_weight - gd0_weight,
        group = str_to_lower(group)) %>%
    drop_na(wt_gain)

litters_data
```

```{r}
litters_data %>%
  lm(wt_gain ~ pups_born_alive, data = .)
```

```{r}
skimr::skim(litters_data)
```

## Other data file formats

Read in an excel file 

```{r}
mlb_df = read_excel("./data/mlb11.xlsx")
```


Read in a SAS file
```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
```


